### ISSUE TITLE
Figure out how to publish this

### ISSUE THREAD

**Issue by hamnis** [hamnis/maven-artifact#10]

**Comment by jimisola** [comment]
What exactly does this issue involve? There seems to be a shell scripts that builds and publishes to pypi. 

But, it be better to use proper Github Actions that triggers in tags. 


https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/

I'm looking for a way to download maven artifacts in python. Found this library, but saw that it has not been updated in a while.

Does the library work with proxies?

**Comment by jimisola** [comment]
@hamnis Provided to PRs. Please note that #12 incorporates changes made in #11 as well since using hatch was a prereq for the GitHub workflow that I created. See PR descriptions for more info.

**Comment by jimisola** [comment]
It would be useful with some basic usage in the README and info on how to use the package as a library or an executable.

**Comment by jimisola** [comment]
I noticed that the github action fails for pypi test. Are you able to look at it?

My mastodon is down (mastodon.se). Let me know if you want to contact me (DM on twitter if so https://twitter.com/jimisola)

**Comment by jimisola** [comment]
Haven't found anyway to use the git-sha. However,

https://github.com/pypa/gh-action-pypi-publish#tolerating-release-package-file-duplicates

If that works then we should be able to close this ticket.

```
 with:
     skip-existing: true

```
Found no other solutions here:
* https://stackoverflow.com/questions/72661025/github-action-publishing-to-both-testpypi-and-pypi-fails
* https://github.com/pypa/gh-action-pypi-publish/issues/16

**Comment by jimisola** [comment]
@hamnis If the solution with skip above works and a decision on minimum python version in taken for #19 then I think it's ready for a new release (a bit eager since I would like to be able to use it for a project next week). Happy belated May 16th btw 🇳🇴

**Comment by hamnis** [comment]
I think #20 should do what we want.
May 17th is the national holiday btw :)

**Comment by hamnis** [comment]
https://github.com/hamnis/maven-artifact/actions/runs/5013751448/jobs/8987232323
@jimisola any idea?

**Comment by jimisola** [comment]
I'm guessing here. The hatch-vcs default to this when there is no version tag set.

There was something about default version: https://github.com/ofek/hatch-vcs#version-source-options

We should be able to set it to say "0.0.0-test" since the publish to pypi will only run if there is a git tag with a version.

**Comment by jimisola** [comment]
'0.1.dev1+g35f1688' is an invalid value for Version. Error: Can't use PEP 440 local versions.

It's the sha for the commit that causes problem I think when looking at [PEP 440](https://peps.python.org/pep-0440/)

See also: https://packaging.python.org/en/latest/specifications/core-metadata/#version

**Comment by jimisola** [comment]
Perhaps, try:

```
[tool.hatch.version]
source = "vcs"
fallback-version = "0.0.0.dev"
```

**Comment by jimisola** [comment]
With the above the version will be the same all the time so [this](https://github.com/hamnis/maven-artifact/issues/10#issuecomment-1546761818) would be needed I think.

**Comment by hamnis** [comment]
This feels bad. Why oh why do they even care if there is something after devN. I'll think about this and try to release this with a tag as is now.

**Comment by jimisola** [comment]
I agree. Might be useful to raise a question with hatch-vcs. How do they do? There should be a best-practise.

It's seems as if[ PEP 440](https://peps.python.org/pep-0440/#public-version-identifiers) devN would only work with build numbers (N) and not "+g35f1688" as in "0.1.dev1+g35f1688".

**Comment by jimisola** [comment]
I filed a question/issue with hatch-vcs: https://github.com/ofek/hatch-vcs/issues/43

**Comment by hamnis** [comment]
@jimisola https://github.com/hamnis/maven-artifact/releases/tag/v0.3.0
