### ISSUE TITLE
Support authentication using token (OAuth)

### ISSUE THREAD

**Issue by jimisola** [hamnis/maven-artifact#23]
## Summary

The [current implementation of authentication](https://github.com/hamnis/maven-artifact/blob/e16db78099f06a0f5c2789438ad008d8e2d10018/src/maven_artifact/requestor.py#LL18C6-L20C92
) only supports basic auth with username and password:

```
if self.username and self.password:
    token = self.username + ":" + self.password
    headers["Authorization"] = "Basic " + base64.b64encode(token.encode()).decode()
```
However, some JFrog, Nexus, GitLab and GitHub and provide (and seem to prefer) tokens:

* JFrog: https://jfrog.com/help/r/jfrog-platform-administration-documentation/authorization-headers
  * Header: "Authorization: Bearer <TOKEN>"
* GitLab: https://docs.gitlab.com/ee/user/packages/maven_repository/#authenticate-to-the-package-registry
  * Different types of tokens and different name for http header property: Private-Token, Deploy-Token, Job-Token
* GitHub: https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-apache-maven-registry#authenticating-with-a-personal-access-token
  * username:token

 ## Proposal
 
 Provide as solution that works with different types of Maven repository vendors with it being transparent (i.e. not having to specify which one to use)
 
 I see the following cases that needs to be supported:
 
 1. username and password (and basic auth token): if both are specified
 2. username and password as a single base64 encoded string: only base64 password is specified (see [here](https://stackoverflow.com/a/45928164))
 3. token with OAuth compliant headers: https://docs.gitlab.com/ee/api/rest/#personalprojectgroup-access-tokens `"Authorization: Bearer <your_access_token>"`
 
 So, the following combinations are then valid:
 
1. username and password (and basic auth token): (1) basic auth
2. password only: (2) base64 basic auth
3. token: OAuth

**Comment by jimisola** [comment]
@hamnis I need this for the project where I use maven artifact, so I'll provide a PR.

Would you mind if I change from getopt to argparse? I believe it is a better option and easier to handle the different mutual exclusive combinations. argparse is part of standard library.

From ChatGPT:

Both `getopt` and `argparse` are modules in Python that facilitate command-line argument parsing. While `getopt` is older and more basic, `argparse` provides a more powerful and flexible approach. Here are the key differences, along with their pros and cons:

`getopt`:
Pros:
1. Simplicity: `getopt` is a straightforward module with a simple interface.
2. Portability: It is available in most Python versions and can be used in different environments.

Cons:
1. Limited functionality: `getopt` has a limited feature set, lacking some advanced argument parsing capabilities.
2. Less intuitive: The usage and syntax of `getopt` can be somewhat complex, especially for handling more complex argument scenarios.
3. No built-in help output: It does not automatically generate help messages for the command-line interface.

`argparse`:
Pros:
1. Rich feature set: `argparse` provides a wide range of functionalities for parsing and handling command-line arguments.
2. Flexibility: It supports positional arguments, optional arguments, subcommands, default values, type validation, and more.
3. Automatic help generation: `argparse` can automatically generate help messages based on the defined arguments and their descriptions.
4. Readability: The code written using `argparse` tends to be more readable and maintainable, especially for complex argument scenarios.
5. Error handling: `argparse` offers built-in error handling and user-friendly error messages.

Cons:
1. Slightly more complex: The API of `argparse` can be initially overwhelming due to its comprehensive feature set.
2. Dependency: `argparse` is part of the standard library, but if you're using an older version of Python, you may need to install the `argparse` package separately.

In general, `argparse` is recommended for most use cases due to its versatility, automatic help generation, and improved readability. However, if you have simple argument parsing needs or require compatibility with older Python versions, `getopt` can still be a viable choice.

**Comment by hamnis** [comment]
Sure. I don't mind 😁
