### ISSUE TITLE
Add version cmd line option (-V, --version)

### ISSUE THREAD

**Issue by lfvjimisola** [hamnis/maven-artifact#30]
Since, Python 3.8 the version is available using `from importlib.metadata import version` and then

```
        argument_parser.add_argument(
            "-V",
            "--version",
            action="version",
            version=version("reqstool"),
        )
```
We can use this version string for #25 as well.

**Comment by lfvjimisola** [comment]
@hamnis I'll provide a PR this week for probably this issue and #25.

**Comment by hamnis** [comment]
@lfvjimisola Nice :)
