### ISSUE TITLE
Ensure python 3 compatibility

### ISSUE THREAD

**Issue by esafak** [hamnis/maven-artifact#4]
[The setup file](https://github.com/hamnis/maven-artifact/blob/master/setup.py) claims compatibility with python 3, but the pip version fails with

``` python
*** Error compiling '/tmp/pip-build-poggx9d1/maven-artifact/maven/downloader.py'...
  File "/tmp/pip-build-poggx9d1/maven-artifact/maven/downloader.py", line 114
    except getopt.GetoptError, err:
                             ^
SyntaxError: invalid syntax

*** Error compiling '/tmp/pip-build-poggx9d1/maven-artifact/maven/requestor.py'...
  File "/tmp/pip-build-poggx9d1/maven-artifact/maven/requestor.py", line 18
    except HTTPError, e:
                    ^
SyntaxError: invalid syntax
```

**Comment by hamnis** [comment]
if you can give me a pointer for how to fix that, i would appreciate that immensely. ( I am not a really a python programmer )

**Comment by esafak** [comment]
[Sure](http://python-future.org/compatible_idioms.html#catching-exceptions):

``` python
# Python 2 and 3:
try:
    ...
except ValueError as e:
    ...
```

**Comment by hamnis** [comment]
I think this should work now in master, can you @esafak please test and see if it does?
If it does, i'll release a new version.

**Comment by esafak** [comment]
That part works, but now you have a `urllib2` reference in `maven/requestor.py` to fix:

``` python
> from urllib2 import Request, urlopen, URLError, HTTPError
ImportError: No module named 'urllib2'
```

[Instead do](http://stackoverflow.com/a/17510727/832188):

``` python
try:
    # For Python 3.0 and later
    from urllib.request import urlopen, Request
    from urllib.error import URLError, HTTPError
except ImportError:
    # Fall back to Python 2's urllib2
    from urllib2 import Request, urlopen, URLError, HTTPError
```

And the relative `requestor` import in `maven/resolver.py` has to be changed to `from .requestor import RequestException`.

**Comment by hamnis** [comment]
fixed.

**Comment by esafak** [comment]
LGTM. Please can you push to pypi?

**Comment by hamnis** [comment]
Done
